### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by mariosuser** [espressif/idf-installer#101]
I am trying to install Installer 2.9 2021-06-15 offline (esp-idf-tools-setup-offline-2.9) and I have this error. Could you help me. Thanks
![Foto](https://user-images.githubusercontent.com/96198063/146235445-be247ce6-cf75-429b-899f-e1cfb315b897.PNG)

**Comment by georgik** [comment]
@mariosuser Thank you for reporting the problem.
It's little bit strange, that `.espressif` is inside another `.espressif` directory.

Could you try the latest installer 2.13-beta-06: https://github.com/espressif/idf-installer/releases/tag/online-2.13-beta-06
Please submit also installation log which is located in user's home `\AppData\Local\Temp\Setup....txt`
