### ISSUE TITLE
Unable to update ESP-IDF v5.0, because of missing requirements.txt

### ISSUE THREAD

**Issue by georgik** [espressif/idf-installer#117]
requirements.txt moved from the root of the project to tools\requirements\requirements.core.txt

Task: Update the installer to recognize also this file.

Workaround: copy files from tools\requirements to the root of ESP-IDF

**Comment by igrr** [comment]
Note that the new requirements.core.txt file doesn't specify version constraints, which are now provided separately. So it's not enough just to handle the new path of the requirements files. More info in https://github.com/espressif/idf-installer/issues/110.
