### ISSUE TITLE
Espressif IDE Java not finding

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/idf-installer#124]
the Amazon JDK is in 
espressif\tools\amazon-corretto-11-x64-windows-jdk
the IDE in 
espressif\tools\espressif-ide\2.4.0\

but it show this Error. 

![image](https://user-images.githubusercontent.com/69573151/157450050-cfb8b4bd-7aae-4e69-9f0a-0a15e8ee523c.png)

either put the jre in the subfolder of the eclipse, 
or set the according -vm Argument, 
or set a PATH to the corretto. (problem if other Eclipse rely on this, 
as Coretto is causing Problems there)

**Comment by kolipakakondal** [comment]
Hi @franz-ms-muc Thanks for reporting. Let us look into this.

**Comment by georgik** [comment]
@franz-ms-muc Thank you for reporting the problem.
The path is not set correctly, because it's fixed to previous minor release of JDK.
Workaround: add path manually.

The new build with the correction should be available shortly.

**Comment by georgik** [comment]
@franz-ms-muc Please re-download new build of the installer from https://github.com/espressif/idf-installer/releases/tag/espressif-ide-2.4.2
The Path environment variable should be updated correctly.
