### ISSUE TITLE
ESP32-C3 LIBUSB error (openocd, probe.rs) (IDFGH-7149)

### ISSUE THREAD

**Issue by TheButlah** [espressif/idf-installer#133]
## Environment

- Development Kit: N/A (custom)
- Kit version (for WroverKit/PicoKit/DevKitC): N/A (custom)
- Module or chip used:  ESP32-C3-MINI-1
- IDF version: v4.4
- Build System:  idf.py
- Compiler version: (crosstool-NG esp-2021r2-patch2) 8.4.0
- Operating System: Windows 10
- (Windows only) environment type: PowerShell.
- Using an IDE? Yes, esp-idf vscode extension
- Power Supply: USB

## Problem Description

I cannot open the built-in USB interface with LIBUSB, no matter whether I use the espressif provided drivers, default windows, or zadig drivers (I tried every combo).

### Expected Behavior

I can use libusb's open function on the device. This would allow me to use [probe.rs](https://probe.rs/).

### Actual Behavior

Depending on which drivers I use (WinUSB, libusbk, usbser, espressif), I get any of the following errors:
`LIBUSB_ERROR_NOT_FOUND`
`LIBUSB_ERROR_ACCESS`

I may have also gotten these, but I'm not sure:
`LIBUSB_ERROR_NOT_FOUND`
`LIBUSB_ERROR_NOT_SUPPORTED`

The strangest part was that when I unchecked "Ignore Hubs or Composite Parents" in Zadig, and made the composite parent use WinUSB, I actually successfully opened the device with libusb, which meant that the probe.rs debugger worked! The issue with this approach was that it removed the two USBCDC interfaces and now it was only a WinUSB interface, which meant no COM port. So I was unable to flash the device at all anymore (at least using the UART setting in esp-idf vscode).

### Steps to reproduce

Have a board using the built-in JTAG/Serial over USB (aka no UART chip, just uses D+ D- pins on esp32c3 directly)

Try using either openocd (which uses libusb), probe.rs debugger (uses libusb), or maybe manually try opening the device with libusb.

### Code to reproduce this issue

cargo.toml should use `probe-rs = "0.12.0"`

```rust
fn main() {
    // Get a list of all available debug probes.
    let probes = probe_rs::Probe::list_all();
    println!("{probes:?}");

    // Use the first probe found.
    let probe = probes[0].open().unwrap();
}
```

## Debug Logs

```
[ESP JTAG (VID: 303a, PID: 1001, EspJtag)]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ProbeCouldNotBeCreated(Rusb(NotFound))', probe\src\main.rs:7:34
stack backtrace:
   0:     0x7ff7a678ae8f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7a678ae8f - std::backtrace_rs::backtrace::trace_unsynchronized        
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7a678ae8f - std::sys_common::backtrace::_print_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff7a678ae8f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff7a679fffa - core::fmt::write
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:1168
   5:     0x7ff7a6788078 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\io\mod.rs:1660
   6:     0x7ff7a678d18b - std::sys_common::backtrace::_print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff7a678d18b - std::sys_common::backtrace::print
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff7a678d18b - std::panicking::default_hook::closure$1
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:211
   9:     0x7ff7a678cc84 - std::panicking::default_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:228
  10:     0x7ff7a678d68c - std::panicking::rust_panic_with_hook
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:606
  11:     0x7ff7a678d54b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:502
  12:     0x7ff7a678b7d7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:139
  13:     0x7ff7a678d249 - std::panicking::begin_panic_handler
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
  14:     0x7ff7a67c6c10 - core::panicking::panic_fmt
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
  15:     0x7ff7a67c6d23 - core::result::unwrap_failed
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\result.rs:1690
  16:     0x7ff7a663174d - enum$<core::result::Result<probe_rs::probe::Probe,enum$<probe_rs::probe::DebugProbeError> > >::unwrap<probe_rs::probe::Probe,enum$<probe_rs::probe::DebugProbeError> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\result.rs:1018
  17:     0x7ff7a66310d0 - probe::main
                               at D:\Ryan\Programming\esp32c3_experiments\probe\src\main.rs:7
  18:     0x7ff7a663156b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:227
  19:     0x7ff7a663164b - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\sys_common\backtrace.rs:123
  20:     0x7ff7a6631441 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\rt.rs:145
  21:     0x7ff7a678a6ef - core::ops::function::impls::impl$2::call_once
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:259
  22:     0x7ff7a678a6ef - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
  23:     0x7ff7a678a6ef - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
  24:     0x7ff7a678a6ef - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
  25:     0x7ff7a678a6ef - std::rt::lang_start_internal::closure$2
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
  26:     0x7ff7a678a6ef - std::panicking::try::do_call
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
  27:     0x7ff7a678a6ef - std::panicking::try
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
  28:     0x7ff7a678a6ef - std::panic::catch_unwind
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
  29:     0x7ff7a678a6ef - std::rt::lang_start_internal
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
  30:     0x7ff7a663140f - std::rt::lang_start<tuple$<> >
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\std\src\rt.rs:144
  31:     0x7ff7a6631136 - main
  32:     0x7ff7a67c5160 - invoke_main
                               at d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33:     0x7ff7a67c5160 - __scrt_common_main_seh
                               at d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34:     0x7ffaaf427034 - BaseThreadInitThunk
  35:     0x7ffaaf562651 - RtlUserThreadStart
```

## See also

My [conversation](https://matrix.to/#/!vhKMWjizPZBgKeknOo:matrix.org/$uRDW1d3xBMQhpPS0BSc7hy4Kg3Xs58ONsbJn0__77nQ?via=matrix.org&via=chat.berline.rs&via=unix.house) on the probe-rs Matrix group where I debugged probe.rs and determined that it was a driver issue with libusb.

My [conversation](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$PF3UlMgOJv9MFAIFybSrZ74IrR4NsSNaFCO6yuxwTJU?via=matrix.org&via=tchncs.de&via=matrix.coredump.ch) on the esp-rs matrix group where I troubleshooted the espressif provided drivers.

**Comment by georgik** [comment]
@TheButlah Thank you for reporting the problem. We will investigate it little bit further.

There are few important things to keep in mind when dealing with Windows drivers.
- Windows drivers are loaded when device is plugged to the system for the first time
- In order to load new or changed driver, it's necessary to unplug and plug the device again
- Windows might refuse to apply driver on existing device, in that case, use the metdhod via Device Manager and delete device with the driver
- When no conflicting driver is in place, run the installation of drivers either by installer or by command: https://github.com/espressif/idf-installer#manual-installation-of-drivers

If the driver is till not applied correctly, please use SysProgs USB Tools to switch/rollback the driver: https://visualgdb.com/UsbDriverTool/

After each change mage sure to unplug and plug the device. In some cases it might be necessary to reboot the computer (often in case of pending system updates)

The logic for deploying the driver is written in Rust: https://github.com/espressif/idf-env/blob/main/src/driver.rs#L117
```
 unsafe {
        // https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupcopyoeminfw
        let result = winapi::um::setupapi::SetupCopyOEMInfW(
```

We welcome any suggestion for the improvement. Probably detection of incorrect driver might help to resolve the situation.

**Comment by Ooyekunle** [comment]
@igrr  or anyone. Could you please help with this openocd issue I have been having.

OS: Windows
IDE: Vs code
Dev board: ESP32-C3 Devkit rev ??

I have just been running into this issue whenever I try to debug using openocd. It's so frustrating.

Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
❌ Error: esp_usb_jtag: could not find or open device!

**Comment by Ooyekunle** [comment]
---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.22000 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Common Files\Pulse Secure\VC142.CRT\X86\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\MinGW\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\leksy\AppData\Local\Microsoft\WindowsApps;C:\Users\leksy\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW\bin; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.67.2 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:\Users\leksy\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin;C:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin;C:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin;C:\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin;C:\Espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Espressif\tools\cmake\3.20.3\bin;C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Espressif\tools\ninja\1.10.2;C:\Espressif\tools\idf-exe\1.0.3;C:\Espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) board/esp32c3-builtin.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Espressif
Git Path (idf.gitPath) C:\Espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin: true
Access to C:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin: true
Access to C:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin: true
Access to C:\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin: true
Access to C:\Espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to C:\Espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to C:\Espressif\tools\cmake\3.20.3\bin: true
Access to C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin: true
Access to C:\Espressif\tools\ninja\1.10.2: true
Access to C:\Espressif\tools\idf-exe\1.0.3: true
Access to C:\Espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 4.4.1
Python version 3.8.7
Python's pip version 22.1.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2022.5.18.1
cffi version: 1.15.0
charset-normalizer version: 2.0.12
click version: 8.1.3
colorama version: 0.4.4
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 37.0.2
ecdsa version: 0.17.0
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.12
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.1
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.1.0
idna version: 3.3
itsdangerous version: 2.0.1
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.8.0
MarkupSafe version: 2.1.1
pip version: 22.1.1
psutil version: 5.9.1
pycparser version: 2.21
pyelftools version: 0.28
pygdbmi version: 0.9.0.2
Pygments version: 2.12.0
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 304
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
setuptools version: 62.3.2
six version: 1.16.0
tqdm version: 4.64.0
urllib3 version: 1.26.9
websocket-client version: 1.3.2
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.3.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from C:\Users\leksy\esp\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:\Users\leksy\.vscode\extensions\espressif.esp-idf-extension-1.4.0\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:\Users\leksy\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Espressif\\tools\\riscv32-esp-elf\\esp-2021r2-patch3-8.4.0\\riscv32-esp-elf\\bin\\riscv32-esp-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            }
        }
    ],
    "version": 4
}
 
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by georgik** [comment]
@Ooyekunle Do you have the board with JTAG or without JTAG?
Please open https://visualgdb.com/UsbDriverTool/ and check status?
You should see:
```
USB Serial Device 303A, 1001, 01
USB JTAG Unit 303A, 1001, 02
```

If the device with 02 is something different, right click the device and choose WinUSB, this will change the driver for one of composite devices.

If you do not see any device 02, then you have board without JTAG and it's not possible to debug it. The only option is to connect ESP-Prog.

**Comment by Ooyekunle** [comment]
@georgik  How do I check status. Do you mean check the status on the website or download the tool and check status?

Thanks

**Comment by georgik** [comment]
@Ooyekunle Please, download the tool. Install the tool. Run the tool. You'll see list of USB devices. Connect the board and new entries should appear in the list. Compare them with the configuration:
```
USB Serial Device 303A, 1001, 01
USB JTAG Unit 303A, 1001, 02
```

**Comment by Ooyekunle** [comment]
@georgik  I just downloaded the tool. It says it extracted but how do I run it as an executeable?

![image](https://user-images.githubusercontent.com/56222583/170232937-c2acf2e3-38af-4c7c-8437-2bf070c8da18.png)

**Comment by Ooyekunle** [comment]
![image](https://user-images.githubusercontent.com/56222583/170233355-d1618e2b-aff2-4f08-a0cf-f52f25e38a6e.png)

**Comment by Ooyekunle** [comment]
@georgik is there  ways I can check the board rev that I have and I was under the impression that all the boards came with internal JTAG debugger. Are there any revision that do not have the JTAG debugger built in our this is just an internal HW problem. Tough luck?

**Comment by georgik** [comment]
@Ooyekunle The screenshot for produced before or after connecting the device?

There is no `303A, 1001, 01`. So the system does not recognize the device.
Do you use USB-A to USB-mini cable or USB-C to USB-mini? Please try also different cable.

I recommend to hit Windows Start, type: Device Manager, hit Enter, click View, click Show hidden devices.
Check whether the list does not contain a device with error mark. Check if you can see a device in section Ports (COM & LPT).

Also run Powershell and type `mode` to get list of all COM ports in the system.

**Comment by Ooyekunle** [comment]
![image](https://user-images.githubusercontent.com/56222583/170236276-881bba06-9dbf-422b-bbcb-53410ac6576b.png)

@georgik So with the USB connection. I can see it's using COM3 port. I have both the USB connection via COM3 and the other breakout connection for debugging according to this https://visualgdb.com/tutorials/esp32/esp32-c3/

**Comment by Ooyekunle** [comment]
@georgik 
![image](https://user-images.githubusercontent.com/56222583/170237185-f4907b21-3d30-4336-8355-bb42598797b0.png)

This is the device that shows up i n the usbdriver tool when I unplugged and plugged the USB according to the connection in this website https://visualgdb.com/tutorials/esp32/esp32-c3/

**Comment by Ooyekunle** [comment]
![B619ADC0-4717-4830-A2A2-4BF320CEC61C](https://user-images.githubusercontent.com/56222583/170238219-bf0ab569-c3df-4d8c-94a7-d29f3c8e3122.jpeg)

I have both connections hooked up.

**Comment by georgik** [comment]
That looks like ESP32-C3 without JTAG which is visible as Silicon Labs CP210x USB to UART Bridge 10C4, EA60.
Please, run in activated ESP-IDF:
`idf.py build flash monitor`
This should give you the revision of the board when monitor is starting.

If JTAG is not present you can use:
- ESP-Prog - https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/jtag-debugging/index.html

Here are instructions from manual: Debugging through the USB interface implemented in ESP32-C3 requires to have a chip with revision 3 or newer. Please use other debugging options (e.g. with ESP-Prog) for chip revision 1 and 2. The easiest way to determine the chip revision is to look for the Chip is ESP32-C3 (revision 3) message near the end of a successful chip flashing done by idf.py flash.

**Comment by Ooyekunle** [comment]
![image](https://user-images.githubusercontent.com/56222583/170239823-5dfdd677-82b5-4189-b313-9f08a67d7594.p

**Comment by Ooyekunle** [comment]
![image](https://user-images.githubusercontent.com/56222583/170239907-ffc302d3-4321-49bb-90ff-11a8ce23cb38.png)

**Comment by Ooyekunle** [comment]
@georgik  This was the console output when I flashed the device. Where can I tell what the revision is?

![image](https://user-images.githubusercontent.com/56222583/170242804-f145aad7-216d-481e-9013-f61592fb2f27.png)

**Comment by igrr** [comment]
Based on VID:PID pair 067B:2303, you have a development board with a PL2303 USB-Serial adapter (perhaps [ESP-C3-32S-Kit](https://www.waveshare.com/wiki/ESP-C3-32S-Kit)?) The drivers for PL2303 are available here: https://www.prolific.com.tw/US/ShowProduct.aspx?p_id=225&pcid=41.

**Comment by Ooyekunle** [comment]
@igrr Does this mean I can’t use the on-chip tag to debug or there’s a chance that I can make it work. If I download the driver, is it going to work or the board Rev just doesn’t support debugging?

thanks @georgik and @igrr

**Comment by igrr** [comment]
@Ooyekunle I think you can, you just need the correct USB cable. I have just edited my comment.

**Comment by Ooyekunle** [comment]
@igrr Do you mean the correct USB cable driver or the correct usb cable itself? Where can I get the correct usb cable ?

**Comment by igrr** [comment]
I meant "correct USB cable".

I think the USB cable you are using is actually a so-called USB-TTL cable, like the one offered here: https://www.robotistan.com/pl2303-usb-ttl-serial-converter-cable. Could you please confirm this? (If you remember where you got the cable from, you can post the link to the product.)

The cable you need is a simple USB cable without any conversion circuits inside. https://www.adafruit.com/product/4448 is one example. You can also make such a cable yourself, if you cut a normal USB A-microB cable in half and solder some dupont wires to the half which has a USB A plug on it.

**Comment by Ooyekunle** [comment]
The cable  came with this ti MCU https://www.ti.com/tool/CC3200-LAUNCHXL

**Comment by Ooyekunle** [comment]
> I meant "correct USB cable".
> 
> I think the USB cable you are using is actually a so-called USB-TTL cable, like the one offered here: https://www.robotistan.com/pl2303-usb-ttl-serial-converter-cable. Could you please confirm this? (If you remember where you got the cable from, you can post the link to the product.)
> 
> The cable you need is a simple USB cable without any conversion circuits inside. https://www.adafruit.com/product/4448 is one example. You can also make such a cable yourself, if you cut a normal USB A-microB cable in half and solder some dupont wires to the half which has a USB A plug on it.

oh, should I just go ahead and get this cable or try to buy a debugger?

**Comment by Ooyekunle** [comment]
@georgik and @igrr Thanks a bunch. I got a new cable made for me in the store and I’m now able to debug 
![Uploading 240AC434-08B8-43B9-9085-23CDD3672105.jpeg…]()

**Comment by Ooyekunle** [comment]
![5CB2A52A-A76E-44BE-A220-5F67A8DFC8F9](https://user-images.githubusercontent.com/56222583/170591695-9bc432d9-d3d4-4661-ab56-bb0cae967f60.jpeg)

**Comment by crNewton** [comment]
> OK, I can install the WinUSB driver through zadig, instead of espressif's installer. This is an acceptable workaround. For those coming across this in the future, be sure that your drivers look like this:
> 
> Device 1: USB Serial ![image](https://user-images.githubusercontent.com/6969415/163137124-79b8a770-bfbf-448d-89a0-9c8e71494c0e.png) This device will remain as the default windows usbser driver, **we shouldn't change it.**
> 
> Device 2: Regular USB ![image](https://user-images.githubusercontent.com/6969415/163137196-cfe660e4-7b4e-436c-8627-50c9d55933f0.png) note that if it shows its signed by espressif instead of libwdi, thats fine, it means the espressif installer worked and you don't need zadig.
> 
> This second device is the one that needs to be installed with Zadig. I used WinUSB as the driver. Be sure you select "install driver" instead of "install WCID driver" in the dropdown. It should look like this: ![image](https://user-images.githubusercontent.com/6969415/163137860-d10a79ed-e1ee-4475-b098-4f87470b9fb5.png)

I can confirm this worked for my ESP32-S3 as well, on Windows 10.

**Comment by georgik** [comment]
Thank you for the updates. The problem seems to be related to current state of drivers in the system. After several attempts we were not able to replicate the problem.

Closing the issue. Feel free to re-open.

@erhankur Please, read the thread, it might be valuable to consider this information when authoring drivers for C2 and C6.

**Comment by weycen** [comment]
我也是win11系统，openocd测试jtag连接 openocd -f board/esp32s3-builtin.cfg 出现这个问题;
按这个

https://github.com/espressif/idf-installer/issues/133#issuecomment-1263204902

使用Zadig把winusb驱动从v10.0.xxx降级到v6.1.xxx后解决, Zadig管理员方式启动，注意Zadig下拉选框要选择Install Driver，而不是默认的Install WCID Driver；
```
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
Error: esp_usb_jtag: could not find or open device! 
```

<img width="573" height="276" alt="Image" src="https://github.com/user-attachments/assets/e6034649-2986-4c47-80c1-93c72bac5d81" />

之后新建esp目标这里，开发板这行就有了，之前是空的；

<img width="774" height="638" alt="Image" src="https://github.com/user-attachments/assets/e0432074-cc5c-4cec-bc46-4ace328e3634" />

**Comment by jakub-kocka** [comment]
@weycen, have you tried Espressif's official JTAG driver?
There is a repository with released drivers for these cases. I believe it might be helpful. However, glad that you have achieved a working solution.

https://github.com/espressif/esp-win-usb-drivers/releases
