### ISSUE TITLE
IDF Installer 2.16 does not work at all. xcopy not an internal or external command 

### ISSUE THREAD

**Issue by ralphde** [espressif/idf-installer#150]
download from mirror slow as well. 2h for nothing.

[Setup Log 2022-10-22 #002.txt](https://github.com/espressif/idf-installer/files/9845126/Setup.Log.2022-10-22.002.txt)

**Comment by georgik** [comment]
@ralphde Thank you for reporting the issue.

Please, can you check whether there is following file: `C:\Windows\system32\xcopy.exe`

**Comment by ralphde** [comment]
Yes, it does exist

Am Di., 8. Nov. 2022 um 12:55 Uhr schrieb Juraj Michálek <
***@***.***>:

**Comment by georgik** [comment]
Thank you for your response @ralphde . It seems that your environment variable `Path` was modified.

Please, check the environment variables in your system. Press the Windows Start logo and type `environment` - select `Edit the system environment variables`. Click `Environment Variables...` at the bottom of the `System Properties` Window. In section `System variables` find variable `Path` and it should contain `C:\Windows\System32'. If the path is missingm add it.

The result should look like:

![image](https://user-images.githubusercontent.com/172276/200580062-f026af4e-692a-4938-88ae-7ebe9e4a71b4.png)

You can test proper configuration by starting PowerShell and typing command `xcopy /?`. It should display help message to xcopy command.

**Comment by ralphde** [comment]
No Sir, is and was set globally. Must have another cause!

[image: image.png]





Am Di., 8. Nov. 2022 um 14:43 Uhr schrieb Juraj Michálek <
***@***.***>:

**Comment by ralphde** [comment]
I can run xcopy from any terminal but indeed I have Norton Antivirus


Am Di., 8. Nov. 2022 um 16:16 Uhr schrieb Juraj Michálek <
***@***.***>:

**Comment by georgik** [comment]
@ralphde Please, can you check environment variable PATHEXT for the value?
It should have value like: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL`

**Comment by georgik** [comment]
@ralphde Problem should be solved in https://github.com/espressif/idf-installer/releases/tag/online-2.17
- added detection of PATHEXT proble in SystemCheck page
- invoked `xcopy.exe` instead of plain `xcopy`
