### ISSUE TITLE
2.19 - 2023-02-01 - Online Installer download/mirror installs Espressif-IDE 2.7.0 instead of 2.8.0

### ISSUE THREAD

**Issue by wreyford** [espressif/idf-installer#165]
The latest **2.19 - 2023-02-01 - Online Installer download/mirror** installer does not install the latest Espressif-IDE, but still installs the older version 27.0 instead of the latest 2.8.0
Please correct.

**Comment by georgik** [comment]
@wreyford : Small update. The installer 2.19 was re-released with this fixed version of Espressif IDE. Since it's minor change.
Feel free to test.

I'll keep this issue open, so that we can have solution in 2.20 where the installer is able to determine latest official release of Espressif IDE.

**Comment by georgik** [comment]
2.21 is pointing to Espressif IDE 2.9.0.
Created issue to track the migration #179
