### ISSUE TITLE
esp-idf-tools-setup-online-2.3.exe 无法获取

### ISSUE THREAD

**Issue by yaozhi1234** [espressif/idf-installer#2]
提供的esp-idf-tools-setup-online-2.3.exe的链接无法访问，链接提示Not Found,我应该怎么获取2.3版本，谢谢

**Comment by georgik** [comment]
Thank you @yaozhi1234 for reporting the issue. Could you give us a hint where the link came from?
Download links should point to version 2.5 or higher.
Please download newer installers from page: https://dl.espressif.com/dl/esp-idf/

**Comment by georgik** [comment]
@yaozhi1234 I found those links in README of the project.
These versions are deprecated and were replaced by newer one. I removed those links from documentation.
Thank you for pointing at that issue. 
Please download latest version from: https://dl.espressif.com/dl/esp-idf/

If you need an older version for some reason, let us know.

**Comment by yaozhi1234** [comment]
Thank you @georgik support.
esp-idf-tools-setup-online-2.3.exe download link is https://github.com/espressif/idf-installer
![image](https://user-images.githubusercontent.com/20679542/114341995-948e9b80-9b8d-11eb-90b9-5f621e341d3f.png)

**Comment by georgik** [comment]
@yaozhi1234 Thank you for the screenshot. The page was updated. I've added link to Download page.
