### ISSUE TITLE
Bad link to ESP-IDF 

### ISSUE THREAD

**Issue by bryghtlabs-richard** [espressif/idf-installer#254]
At https://dl.espressif.com/dl/esp-idf/, the table at the bottom has:

Offline Installer v4.4.82024-07-01 Download: https://github.com/espressif/idf-installer/releases/download/offline-4.4.8/esp-idf-tools-setup-offline-4.4.8.exe but it 404s. The buttons toward the top of the page for 4.4.8 link to https://dl.espressif.com/dl/idf-installer/esp-idf-tools-setup-offline-4.4.8.exe? , which works.

**Comment by jakub-kocka** [comment]
Thank you for pointing this out, @bryghtlabs-richard. We will prepare a fix for it.
