### ISSUE TITLE
ESP-IDF v5.3.1 install-idf.ps1 has a typographical error on line 32 causing the script to fail

### ISSUE THREAD

**Issue by mbratch** [espressif/idf-installer#276]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

Always if running the script without special options that preset the python path.

### Expected behavior

Run without errors if the appropriate environment variables (IDF_PATH, IDF_TOOLS_PATH) are set correctly.

### Actual behavior (suspected bug)

An error occurs on this line (75) in the ps1 script because the python path is invalid:

`$IdfPythonDir = (Get-Item $PythonCommand).Directory.FullName`

The reason the path is invalid is because there is a typo on line 32:

`$PythonCommand=idf-env config get --property python --idf-path "$IDF_PATH\"`

The trailing backslash should not be here. This line should be:

`$PythonCommand=idf-env config get --property python --idf-path "$IDF_PATH"`

### Error logs or terminal output

```shell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Loading personal and system profiles took 1636ms.
Setting PYTHONNOUSERSITE, was not set
Get-Item : Cannot find path 'C:\Users\bra1fp\esp\v5.3.1\esp-idf\null' because it does not exist.
At C:\Espressif\Initialize-Idf.ps1:75 char:18
+ $IdfPythonDir = (Get-Item $PythonCommand).Directory.FullName
+                  ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\bra1fp\esp\v5.3.1\esp-idf\null:String) [Get-Item], ItemNotFoun
   dException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

```
```


### Steps to reproduce the behavior

(1) Properly set IDF_PATH and IDF_TOOLS_PATH
(2) Run the initialize-idf.ps1 script
(3) Observe error

### Project release version

ESP-IDF v5.3.1

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Windows

### Operating system version

Windows 11 23H2

### Shell

PowerShell

### Additional context

_No response_

**Comment by jakub-kocka** [comment]
Hello @mbratch,

Thank you for pointing this out. We will fix this.
