### ISSUE TITLE
McAfee antivirus blocks installation for long period of time

### ISSUE THREAD

**Issue by JurajSadel** [espressif/idf-installer#39]
How to simulate: Start installer, click install and it will block the installation

**Comment by georgik** [comment]
Identification of antivirus diagnosed by idf-env: `McAfee VirusScan`

Problem: Significant blocking delay when launching idf-env for driver installation in elevated privileges mode - 10+ seconds

Workaround: In component selection uncheck `Drivers - Requires elevation of privileges`. The installation will pass without waiting. Drivers could be installed later on by command:
```
idf-env.exe driver install --espressif --ftdi --silabs
```

Note: Turning off `Real-time scanning` does not have impact on the delay

Possible solution: Launch idf-env in background

Requested change: Inform user on diagnostic screen about potential problem with this particular antivirus.

**Comment by georgik** [comment]
Routing invoking idf-env is blocking. It should be changed to async mode.

**Comment by georgik** [comment]
Solved in release in 2.11
