### ISSUE TITLE
Doesn't Support Windows Arm architecture

### ISSUE THREAD

**Issue by drony** [espressif/idf-installer#87]
I think just installer restriction. so many x86 and x64 apps works normally.
I tried Mac OS with parallels and windows 11 insider

error message attached
![Capture](https://user-images.githubusercontent.com/101887/140625023-72b5a93f-cb74-41b2-85b8-2baa627302a9.PNG)

**Comment by drony** [comment]
ok i fixed 
i deleted to lines from idfToolsSetup.iss and compiled from source code. works very well

ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

**Comment by georgik** [comment]
Hi @drony . Thank you for the report.

The installer is intended to work only on Windows x64. Removing those lines might allow the installation on Windows 32-bit which is not supported by several tools inside ESP-IDF.

BTW: Is there a reason not to use native ESP-IDF for macOS and run it in Parallels? It should work pretty well with M1. I'm curious about the use-case.

**Comment by georgik** [comment]
Closing this issue since ESP-IDF is natively supported on macOS aarch64 and macOS x86_64. It's also supported in Podman/Docker container.

Feel free to reopen the issue and add reason why it might make sems to run ESP-IDF in emulated environment like Parallels.

**Comment by cmsd2** [comment]
thanks. i used this workaround to get the installer to run on Windows-on-Arm on a snapdragon x elite
