### ISSUE TITLE
Add workflow which update https://dl.espressif.com/dl/esp-idf/

### ISSUE THREAD

**Issue by georgik** [espressif/idf-installer#91]
Add dispatch workflow which uploads file https://github.com/espressif/idf-installer/blob/main/src/Resources/download/index.html to https://dl.espressif.com/dl/esp-idf/.
Motivation: upload Download page during release process directly from GitHub.

**Comment by JurajSadel** [comment]
@georgik  PTAL https://github.com/espressif/idf-installer/blob/main/.github/workflows/update-index.yml

**Comment by georgik** [comment]
Thank you @JurajSadel . The solution works.
